debugger;
try {
    const t = 4;
    t = 5;
} catch (exception) {
    console.log("Blad w przypisaniu");
}

